#ifndef PERIPHERALS_EXCEPTION_H
#define PERIPHERALS_EXCEPTION_H

#include "base.h"

#define INTERRUPT_BASE  (MMIO_BASE + 0xB000)

#define IRQ_PENDING_1   (INTERRUPT_BASE + 0x204)
#define ENABLE_IRQs1    (INTERRUPT_BASE + 0x210)

#define CORE0_IRQ_SOURCE        0x40000060

#endif /* PERIPHERALS_EXCEPTION_H */