#ifndef __GPIO_H__
#define __GPIO_H__

#define GPIO_BASE           0x3f200000
#define GPFSEL0             (GPIO_BASE + 0x0)
#define GPFSEL1             (GPIO_BASE + 0x4)
#define GPFSEL2             (GPIO_BASE + 0x8)
#define GPFSEL3             (GPIO_BASE + 0xc)
#define GPFSEL4             (GPIO_BASE + 0x10)
#define GPFSEL5             (GPIO_BASE + 0x14)
#define GPSET0              (GPIO_BASE + 0x1c)
#define GPSET1              (GPIO_BASE + 0x20)
#define GPCLR0              (GPIO_BASE + 0x28)
#define GPCLR1              (GPIO_BASE + 0x2c)
#define GPLEV0              (GPIO_BASE + 0x34)
#define GPLEV1              (GPIO_BASE + 0x38)
#define GPEDS0              (GPIO_BASE + 0x40)
#define GPEDS1              (GPIO_BASE + 0x44)
#define GPREN0              (GPIO_BASE + 0x4c)
#define GPREN1              (GPIO_BASE + 0x50)
#define GPFEN0              (GPIO_BASE + 0x58)
#define GPFEN1              (GPIO_BASE + 0x5c)
#define GPHEN0              (GPIO_BASE + 0x64)
#define GPHEN1              (GPIO_BASE + 0x68)
#define GPLEN0              (GPIO_BASE + 0x70)
#define GPLEN1              (GPIO_BASE + 0x74)
#define GPAREN0             (GPIO_BASE + 0x7c)
#define GPAREN1             (GPIO_BASE + 0x80)
#define GPAFEN0             (GPIO_BASE + 0x88)
#define GPAFEN1             (GPIO_BASE + 0x8c)
#define GPPUD               (GPIO_BASE + 0x94)
#define GPPUDCLK0           (GPIO_BASE + 0x98)
#define GPPUDCLK1           (GPIO_BASE + 0x9c)

#endif