#define ENOENT 2
#define ESRCH 3
#define EINTR 4
#define EIO 5
#define ENOMEM 12
#define EBUSY 16
#define EEXIST 17
#define ENOTDIR 20
#define EISDIR 21
#define EINVAL 22
#define EFBIG 27
#define ENOSYS 38
#define ELOOP 40
